Bugfix of macau.pyx
Hi Jaak.
When I run macau with "save_prefix" option in Python 3.5.4, I got an error like the following.
Traceback (most recent call last):
  File "./run_macau.py", line 29, in <module>
    save_prefix = 'mymodel')
  File "python/macau/macau.pyx", line 359, in macau.macau.macau (python/macau/macau.cpp:11838)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (python/macau/macau.cpp:14566)
TypeError: expected bytes, str found

Therefore, I made a bit change in macau.pyx so as to be compatible with Python3.
Could you please confirm it?